
python3 dots_array.py -M 3 -N 3 --vmin 0 --vmax 2 --vstep 0.01 --vr 0 --vg-avg 0 --vg-std 0 --c-avg 1 --c-std 0.1 --cg-avg 10 --cg-std 0 --r-avg 1 --r-std 2 --rg-avg 1000 --rg-std 0 --repeats 20 --n-avg 0 --n-std 0 --q-avg 0 --q-std 0 -T 0 --distribution exp --custom-rh "" --custom-rv "" --custom-ch "" --custom-cv "" --file-name c_std_0.1_r_std_2_run_1 -o 3X3_array_statistics    --resume --symmetric-v

Loading array parameters
Normal prototype array was created
Starting parallel run
Saving results
total steps = 46639904
total steps = 48571734
total steps = 50568674
total steps = 57842744
total steps = 67310766
total steps = 67310766
total steps = 67310766
total steps = 67264858
total steps = 68544119
total steps = 68544119
total steps = 68544119
total steps = 68544119
total steps = 68544119
total steps = 68544119
total steps = 69716872
total steps = 69716872
total steps = 70949184
total steps = 68544119
total steps = 69716872
total steps = 68544119
Traceback (most recent call last):
  File "dots_array.py", line 1672, in <module>
    checkSteadyState=False, superconducting=sc, gap=gap)
  File "dots_array.py", line 1368, in runFullSimulation
    avgIErr = np.sqrt(np.sum(np.array(IsErr)**2, axis=0))/len(IsErr)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1930, in sum
    initial=initial)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: operands could not be broadcast together with shapes (400,) (399,) 
